export const MEDIA = [
  { id: "all", label: "All eras" },
  { id: "hotd", label: "House of the Dragon" },
  { id: "knight", label: "A Knight of the Seven Kingdoms" },
  { id: "got", label: "Game of Thrones" },
  { id: "books", label: "Books" }
];

export const HOUSES = [
  { id: "all", label: "All houses", color: "#d8c48a" },
  { id: "targaryen", label: "Targaryen", color: "#b92f3a" },
  { id: "stark", label: "Stark", color: "#9aa4aa" },
  { id: "baratheon", label: "Baratheon", color: "#d5ad42" },
  { id: "lannister", label: "Lannister", color: "#c6863d" },
  { id: "velaryon", label: "Velaryon", color: "#7fb8c7" },
  { id: "hightower", label: "Hightower", color: "#89a96b" },
  { id: "other", label: "Other", color: "#8f8270" }
];

export const BOOKS = [
  {
    id: "agot",
    title: "A Game of Thrones",
    year: "1996",
    era: "War of the Five Kings begins",
    media: ["books", "got"]
  },
  {
    id: "acok",
    title: "A Clash of Kings",
    year: "1998",
    era: "Five kings, old magic, broken claims",
    media: ["books", "got"]
  },
  {
    id: "asos",
    title: "A Storm of Swords",
    year: "2000",
    era: "The realm fractures",
    media: ["books", "got"]
  },
  {
    id: "affc",
    title: "A Feast for Crows",
    year: "2005",
    era: "Aftermath in King's Landing and the Riverlands",
    media: ["books"]
  },
  {
    id: "adwd",
    title: "A Dance with Dragons",
    year: "2011",
    era: "Daenerys, Jon, and the northern war",
    media: ["books", "got"]
  },
  {
    id: "hedge",
    title: "The Hedge Knight",
    year: "1998",
    era: "Dunk and Egg at Ashford",
    media: ["books", "knight"]
  },
  {
    id: "sworn",
    title: "The Sworn Sword",
    year: "2003",
    era: "The Reach after the Blackfyre Rebellion",
    media: ["books", "knight"]
  },
  {
    id: "mystery",
    title: "The Mystery Knight",
    year: "2010",
    era: "Whitewalls and Blackfyre echoes",
    media: ["books", "knight"]
  },
  {
    id: "akotsk",
    title: "A Knight of the Seven Kingdoms",
    year: "2015",
    era: "Collected Dunk and Egg novellas",
    media: ["books", "knight"]
  },
  {
    id: "fireblood",
    title: "Fire & Blood",
    year: "2018",
    era: "Targaryen rule through the Dance",
    media: ["books", "hotd"]
  },
  {
    id: "twoiaf",
    title: "The World of Ice & Fire",
    year: "2014",
    era: "Dynastic history and atlas lore",
    media: ["books", "hotd", "got", "knight"]
  },
  {
    id: "rise",
    title: "The Rise of the Dragon",
    year: "2022",
    era: "Illustrated Targaryen history",
    media: ["books", "hotd"]
  },
  {
    id: "winds",
    title: "The Winds of Winter",
    year: "Unreleased",
    era: "Announced continuation",
    media: ["books"]
  },
  {
    id: "dream",
    title: "A Dream of Spring",
    year: "Unreleased",
    era: "Planned conclusion",
    media: ["books"]
  }
];

export const PEOPLE = [
  {
    id: "aegon_i",
    name: "Aegon I",
    epithet: "The Conqueror",
    house: "targaryen",
    x: 620,
    y: 70,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf", "rise"],
    parents: [],
    spouses: ["rhaenys_t", "visenya_t"],
    note: "United six kingdoms and forged the Iron Throne."
  },
  {
    id: "rhaenys_t",
    name: "Rhaenys Targaryen",
    epithet: "Sister-wife",
    house: "targaryen",
    x: 450,
    y: 70,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: [],
    spouses: ["aegon_i"],
    note: "One of Aegon's two sister-wives and a queen of the Conquest."
  },
  {
    id: "visenya_t",
    name: "Visenya Targaryen",
    epithet: "Sister-wife",
    house: "targaryen",
    x: 790,
    y: 70,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: [],
    spouses: ["aegon_i"],
    note: "A conqueror queen and mother of Maegor."
  },
  {
    id: "aenys_i",
    name: "Aenys I",
    house: "targaryen",
    x: 550,
    y: 175,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: ["aegon_i", "rhaenys_t"],
    spouses: [],
    note: "Second king on the Iron Throne."
  },
  {
    id: "maegor_i",
    name: "Maegor I",
    epithet: "The Cruel",
    house: "targaryen",
    x: 780,
    y: 175,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: ["aegon_i", "visenya_t"],
    spouses: [],
    note: "Usurped his nephew's claim and ruled through terror."
  },
  {
    id: "jaehaerys_i",
    name: "Jaehaerys I",
    epithet: "The Conciliator",
    house: "targaryen",
    x: 560,
    y: 285,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf", "rise"],
    parents: ["aenys_i"],
    spouses: ["alysanne_t"],
    note: "His long reign shaped the realm and the succession crisis that followed."
  },
  {
    id: "alysanne_t",
    name: "Alysanne",
    epithet: "Good Queen",
    house: "targaryen",
    x: 380,
    y: 285,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: ["aenys_i"],
    spouses: ["jaehaerys_i"],
    note: "Jaehaerys's sister-wife and a decisive queen in her own right."
  },
  {
    id: "aemon_prince",
    name: "Aemon",
    epithet: "Prince of Dragonstone",
    house: "targaryen",
    x: 420,
    y: 395,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: ["jaehaerys_i", "alysanne_t"],
    spouses: ["jocelyn_baratheon"],
    note: "Heir whose death opened a succession question."
  },
  {
    id: "baelon_prince",
    name: "Baelon",
    epithet: "The Brave",
    house: "targaryen",
    x: 650,
    y: 395,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf"],
    parents: ["jaehaerys_i", "alysanne_t"],
    spouses: ["alyssa_t"],
    note: "Father of Viserys I and Daemon."
  },
  {
    id: "alyssa_t",
    name: "Alyssa",
    house: "targaryen",
    x: 820,
    y: 395,
    media: ["books", "hotd"],
    books: ["fireblood"],
    parents: ["jaehaerys_i", "alysanne_t"],
    spouses: ["baelon_prince"],
    note: "Mother of Viserys I and Daemon."
  },
  {
    id: "jocelyn_baratheon",
    name: "Jocelyn Baratheon",
    house: "baratheon",
    x: 220,
    y: 395,
    media: ["books", "hotd"],
    books: ["fireblood"],
    parents: [],
    spouses: ["aemon_prince"],
    note: "Baratheon blood enters the Targaryen succession through Rhaenys."
  },
  {
    id: "rhaenys_queen",
    name: "Rhaenys",
    epithet: "The Queen Who Never Was",
    house: "targaryen",
    x: 360,
    y: 505,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["aemon_prince", "jocelyn_baratheon"],
    spouses: ["corlys_velaryon"],
    note: "Passed over by the Great Council, later a major power in the Dance."
  },
  {
    id: "corlys_velaryon",
    name: "Corlys Velaryon",
    epithet: "Sea Snake",
    house: "velaryon",
    x: 170,
    y: 505,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: [],
    spouses: ["rhaenys_queen"],
    note: "Lord of the tides and patriarch of a dragonriding Velaryon branch."
  },
  {
    id: "viserys_i",
    name: "Viserys I",
    house: "targaryen",
    x: 660,
    y: 505,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["baelon_prince", "alyssa_t"],
    spouses: ["aemma_arryn", "alicent_hightower"],
    note: "Named Rhaenyra heir, but his second marriage produced rival claimants."
  },
  {
    id: "daemon_t",
    name: "Daemon Targaryen",
    house: "targaryen",
    x: 520,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["baelon_prince", "alyssa_t"],
    spouses: ["laena_velaryon", "rhaenyra"],
    note: "Brother to Viserys I and husband to Rhaenyra."
  },
  {
    id: "aemma_arryn",
    name: "Aemma Arryn",
    house: "other",
    x: 815,
    y: 505,
    media: ["books", "hotd"],
    books: ["fireblood"],
    parents: [],
    spouses: ["viserys_i"],
    note: "Mother of Rhaenyra."
  },
  {
    id: "alicent_hightower",
    name: "Alicent Hightower",
    house: "hightower",
    x: 1010,
    y: 505,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: [],
    spouses: ["viserys_i"],
    note: "Mother of Aegon II, Helaena, Aemond, and Daeron."
  },
  {
    id: "laena_velaryon",
    name: "Laena Velaryon",
    house: "velaryon",
    x: 345,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood"],
    parents: ["corlys_velaryon", "rhaenys_queen"],
    spouses: ["daemon_t"],
    note: "Daughter of Corlys and Rhaenys; Daemon's second wife."
  },
  {
    id: "laenor_velaryon",
    name: "Laenor Velaryon",
    house: "velaryon",
    x: 700,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["corlys_velaryon", "rhaenys_queen"],
    spouses: ["rhaenyra"],
    note: "Rhaenyra's first husband and legal father of her elder sons."
  },
  {
    id: "rhaenyra",
    name: "Rhaenyra Targaryen",
    house: "targaryen",
    x: 820,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["viserys_i", "aemma_arryn"],
    spouses: ["laenor_velaryon", "daemon_t"],
    note: "Named heir to Viserys I; claimant and brief ruler in the Dance."
  },
  {
    id: "aegon_ii",
    name: "Aegon II",
    house: "targaryen",
    x: 1030,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["viserys_i", "alicent_hightower"],
    spouses: ["helaena_t"],
    note: "Crowned against Rhaenyra, making the Dance inevitable."
  },
  {
    id: "helaena_t",
    name: "Helaena",
    house: "targaryen",
    x: 1210,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["viserys_i", "alicent_hightower"],
    spouses: ["aegon_ii"],
    note: "Sister-wife to Aegon II."
  },
  {
    id: "aemond_t",
    name: "Aemond",
    house: "targaryen",
    x: 1390,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["viserys_i", "alicent_hightower"],
    spouses: [],
    note: "A major Green prince and dragonrider."
  },
  {
    id: "daeron_daring",
    name: "Daeron",
    epithet: "The Daring",
    house: "targaryen",
    x: 1535,
    y: 615,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["viserys_i", "alicent_hightower"],
    spouses: [],
    note: "Youngest son of Viserys I and Alicent."
  },
  {
    id: "jacaerys",
    name: "Jacaerys Velaryon",
    house: "velaryon",
    x: 640,
    y: 730,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["rhaenyra"],
    legalParents: ["laenor_velaryon"],
    spouses: [],
    note: "Rhaenyra's eldest son and heir during the Dance."
  },
  {
    id: "lucerys",
    name: "Lucerys Velaryon",
    house: "velaryon",
    x: 810,
    y: 730,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["rhaenyra"],
    legalParents: ["laenor_velaryon"],
    spouses: [],
    note: "His mission to Storm's End becomes a turning point."
  },
  {
    id: "joffrey_velaryon",
    name: "Joffrey Velaryon",
    house: "velaryon",
    x: 980,
    y: 730,
    media: ["books", "hotd"],
    books: ["fireblood", "rise"],
    parents: ["rhaenyra"],
    legalParents: ["laenor_velaryon"],
    spouses: [],
    note: "Rhaenyra's third Velaryon son."
  },
  {
    id: "aegon_iii",
    name: "Aegon III",
    house: "targaryen",
    x: 720,
    y: 845,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf", "rise"],
    parents: ["daemon_t", "rhaenyra"],
    spouses: [],
    note: "Survived the Dance and inherited a broken dynasty."
  },
  {
    id: "viserys_ii",
    name: "Viserys II",
    house: "targaryen",
    x: 900,
    y: 845,
    media: ["books", "hotd"],
    books: ["fireblood", "twoiaf", "rise"],
    parents: ["daemon_t", "rhaenyra"],
    spouses: [],
    note: "Younger son of Daemon and Rhaenyra; later king."
  },
  {
    id: "daeron_i",
    name: "Daeron I",
    epithet: "The Young Dragon",
    house: "targaryen",
    x: 560,
    y: 960,
    media: ["books"],
    books: ["twoiaf"],
    parents: ["aegon_iii"],
    spouses: [],
    note: "Conquered Dorne, briefly."
  },
  {
    id: "baelor_i",
    name: "Baelor I",
    epithet: "The Blessed",
    house: "targaryen",
    x: 720,
    y: 960,
    media: ["books"],
    books: ["twoiaf"],
    parents: ["aegon_iii"],
    spouses: [],
    note: "A pious king whose reign reshaped royal politics."
  },
  {
    id: "daena_t",
    name: "Daena",
    epithet: "The Defiant",
    house: "targaryen",
    x: 880,
    y: 960,
    media: ["books"],
    books: ["twoiaf"],
    parents: ["aegon_iii"],
    spouses: [],
    note: "Mother of Daemon Blackfyre."
  },
  {
    id: "aegon_iv",
    name: "Aegon IV",
    epithet: "The Unworthy",
    house: "targaryen",
    x: 1040,
    y: 960,
    media: ["books", "knight"],
    books: ["twoiaf", "mystery"],
    parents: ["viserys_ii"],
    spouses: ["naerys_t"],
    note: "His legitimized bastards seeded the Blackfyre rebellions."
  },
  {
    id: "naerys_t",
    name: "Naerys",
    house: "targaryen",
    x: 1210,
    y: 960,
    media: ["books"],
    books: ["twoiaf"],
    parents: ["viserys_ii"],
    spouses: ["aegon_iv"],
    note: "Sister-wife to Aegon IV and mother of Daeron II."
  },
  {
    id: "aemon_dragonknight",
    name: "Aemon",
    epithet: "Dragonknight",
    house: "targaryen",
    x: 1390,
    y: 960,
    media: ["books", "knight"],
    books: ["twoiaf", "mystery"],
    parents: ["viserys_ii"],
    spouses: [],
    note: "Legendary Kingsguard knight."
  },
  {
    id: "daemon_blackfyre",
    name: "Daemon Blackfyre",
    house: "targaryen",
    x: 875,
    y: 1080,
    media: ["books", "knight"],
    books: ["twoiaf", "sworn", "mystery"],
    parents: ["aegon_iv", "daena_t"],
    spouses: [],
    note: "Great bastard whose claim split the realm."
  },
  {
    id: "daeron_ii",
    name: "Daeron II",
    epithet: "The Good",
    house: "targaryen",
    x: 1110,
    y: 1080,
    media: ["books", "knight"],
    books: ["twoiaf", "hedge", "sworn", "mystery"],
    parents: ["aegon_iv", "naerys_t"],
    spouses: [],
    note: "Brought Dorne into the realm by marriage."
  },
  {
    id: "baelor_breakspear",
    name: "Baelor Breakspear",
    house: "targaryen",
    x: 860,
    y: 1195,
    media: ["books", "knight"],
    books: ["hedge", "akotsk"],
    parents: ["daeron_ii"],
    spouses: [],
    note: "Prince of Dragonstone and champion at Ashford."
  },
  {
    id: "aerys_i",
    name: "Aerys I",
    house: "targaryen",
    x: 1040,
    y: 1195,
    media: ["books", "knight"],
    books: ["twoiaf", "sworn", "mystery"],
    parents: ["daeron_ii"],
    spouses: [],
    note: "King during Dunk and Egg's early wanderings."
  },
  {
    id: "maekar_i",
    name: "Maekar I",
    house: "targaryen",
    x: 1220,
    y: 1195,
    media: ["books", "knight"],
    books: ["hedge", "akotsk", "twoiaf"],
    parents: ["daeron_ii"],
    spouses: [],
    note: "Father of Egg and later king."
  },
  {
    id: "aerion_brightflame",
    name: "Aerion Brightflame",
    house: "targaryen",
    x: 1400,
    y: 1195,
    media: ["books", "knight"],
    books: ["hedge", "akotsk"],
    parents: ["maekar_i"],
    spouses: [],
    note: "Maekar's volatile son."
  },
  {
    id: "aegon_v",
    name: "Aegon V",
    epithet: "Egg",
    house: "targaryen",
    x: 1230,
    y: 1310,
    media: ["books", "knight"],
    books: ["hedge", "sworn", "mystery", "akotsk", "twoiaf"],
    parents: ["maekar_i"],
    spouses: ["betha_blackwood"],
    note: "Dunk's squire, later king and ancestor of Daenerys and Jon."
  },
  {
    id: "betha_blackwood",
    name: "Betha Blackwood",
    house: "other",
    x: 1030,
    y: 1310,
    media: ["books"],
    books: ["twoiaf"],
    parents: [],
    spouses: ["aegon_v"],
    note: "Queen consort of Aegon V."
  },
  {
    id: "duncan_tall",
    name: "Duncan the Tall",
    epithet: "Dunk",
    house: "other",
    x: 1450,
    y: 1310,
    media: ["books", "knight"],
    books: ["hedge", "sworn", "mystery", "akotsk"],
    parents: [],
    spouses: [],
    note: "Hedge knight, Egg's sworn companion, and future Lord Commander."
  },
  {
    id: "jaehaerys_ii",
    name: "Jaehaerys II",
    house: "targaryen",
    x: 1190,
    y: 1425,
    media: ["books"],
    books: ["twoiaf"],
    parents: ["aegon_v", "betha_blackwood"],
    spouses: [],
    note: "Short-reigned king and father of Aerys II and Rhaella."
  },
  {
    id: "aerys_ii",
    name: "Aerys II",
    epithet: "The Mad King",
    house: "targaryen",
    x: 1040,
    y: 1535,
    media: ["books", "got"],
    books: ["agot", "twoiaf"],
    parents: ["jaehaerys_ii"],
    spouses: ["rhaella_t"],
    note: "Last Targaryen king before Robert's Rebellion."
  },
  {
    id: "rhaella_t",
    name: "Rhaella",
    house: "targaryen",
    x: 1210,
    y: 1535,
    media: ["books", "got"],
    books: ["agot", "twoiaf"],
    parents: ["jaehaerys_ii"],
    spouses: ["aerys_ii"],
    note: "Mother of Rhaegar, Viserys, and Daenerys."
  },
  {
    id: "rhaegar_t",
    name: "Rhaegar Targaryen",
    house: "targaryen",
    x: 900,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "asos", "adwd", "twoiaf"],
    parents: ["aerys_ii", "rhaella_t"],
    spouses: ["elia_martell", "lyanna_stark"],
    note: "Prince whose choices ignited the rebellion and Jon's hidden lineage."
  },
  {
    id: "elia_martell",
    name: "Elia Martell",
    house: "other",
    x: 730,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "asos", "adwd"],
    parents: [],
    spouses: ["rhaegar_t"],
    note: "Princess of Dorne and Rhaegar's wife."
  },
  {
    id: "viserys_beggar",
    name: "Viserys",
    epithet: "Beggar King",
    house: "targaryen",
    x: 1110,
    y: 1645,
    media: ["books", "got"],
    books: ["agot"],
    parents: ["aerys_ii", "rhaella_t"],
    spouses: [],
    note: "Exiled claimant before Daenerys rises."
  },
  {
    id: "daenerys_t",
    name: "Daenerys Targaryen",
    house: "targaryen",
    x: 1300,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "adwd"],
    parents: ["aerys_ii", "rhaella_t"],
    spouses: [],
    note: "Dragon queen and last public Targaryen claimant in the show era."
  },
  {
    id: "rickard_stark",
    name: "Rickard Stark",
    house: "stark",
    x: 210,
    y: 1310,
    media: ["books", "got"],
    books: ["agot", "twoiaf"],
    parents: [],
    spouses: ["lyarra_stark"],
    note: "Lord of Winterfell before Robert's Rebellion."
  },
  {
    id: "lyarra_stark",
    name: "Lyarra Stark",
    house: "stark",
    x: 65,
    y: 1310,
    media: ["books"],
    books: ["twoiaf"],
    parents: [],
    spouses: ["rickard_stark"],
    note: "Mother of Brandon, Eddard, Lyanna, and Benjen."
  },
  {
    id: "brandon_stark_uncle",
    name: "Brandon Stark",
    house: "stark",
    x: 80,
    y: 1425,
    media: ["books", "got"],
    books: ["agot"],
    parents: ["rickard_stark", "lyarra_stark"],
    spouses: [],
    note: "Eddard's elder brother, killed by Aerys II."
  },
  {
    id: "eddard_stark",
    name: "Eddard Stark",
    epithet: "Ned",
    house: "stark",
    x: 260,
    y: 1425,
    media: ["books", "got"],
    books: ["agot"],
    parents: ["rickard_stark", "lyarra_stark"],
    spouses: ["catelyn_stark"],
    note: "Lord of Winterfell and Jon's public father."
  },
  {
    id: "lyanna_stark",
    name: "Lyanna Stark",
    house: "stark",
    x: 465,
    y: 1535,
    media: ["books", "got"],
    books: ["agot", "asos", "adwd"],
    parents: ["rickard_stark", "lyarra_stark"],
    spouses: ["rhaegar_t"],
    note: "Jon's mother and the hidden Stark-Targaryen bridge."
  },
  {
    id: "benjen_stark",
    name: "Benjen Stark",
    house: "stark",
    x: 455,
    y: 1425,
    media: ["books", "got"],
    books: ["agot"],
    parents: ["rickard_stark", "lyarra_stark"],
    spouses: [],
    note: "Night's Watch ranger and Eddard's brother."
  },
  {
    id: "catelyn_stark",
    name: "Catelyn Stark",
    house: "other",
    x: 260,
    y: 1535,
    media: ["books", "got"],
    books: ["agot", "acok", "asos"],
    parents: [],
    spouses: ["eddard_stark"],
    note: "Born Tully, Lady of Winterfell."
  },
  {
    id: "robb_stark",
    name: "Robb Stark",
    house: "stark",
    x: 70,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos"],
    parents: ["eddard_stark", "catelyn_stark"],
    spouses: [],
    note: "King in the North during the War of the Five Kings."
  },
  {
    id: "sansa_stark",
    name: "Sansa Stark",
    house: "stark",
    x: 225,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "affc"],
    parents: ["eddard_stark", "catelyn_stark"],
    spouses: [],
    note: "Political survivor and Queen in the North in the show ending."
  },
  {
    id: "arya_stark",
    name: "Arya Stark",
    house: "stark",
    x: 380,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "affc", "adwd"],
    parents: ["eddard_stark", "catelyn_stark"],
    spouses: [],
    note: "Faceless-trained Stark daughter."
  },
  {
    id: "bran_stark",
    name: "Bran Stark",
    house: "stark",
    x: 535,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "adwd"],
    parents: ["eddard_stark", "catelyn_stark"],
    spouses: [],
    note: "Chosen king of the Six Kingdoms in the show after the Iron Throne is destroyed."
  },
  {
    id: "rickon_stark",
    name: "Rickon Stark",
    house: "stark",
    x: 690,
    y: 1755,
    media: ["books", "got"],
    books: ["agot", "acok", "adwd"],
    parents: ["eddard_stark", "catelyn_stark"],
    spouses: [],
    note: "Youngest Stark child."
  },
  {
    id: "jon_snow",
    name: "Jon Snow",
    epithet: "Aegon in show canon",
    house: "stark",
    x: 640,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "adwd"],
    parents: ["rhaegar_t", "lyanna_stark"],
    legalParents: ["eddard_stark"],
    spouses: [],
    note: "Raised as Ned's bastard; show canon reveals Rhaegar and Lyanna as parents."
  },
  {
    id: "steffon_baratheon",
    name: "Steffon Baratheon",
    house: "baratheon",
    x: 1230,
    y: 1425,
    media: ["books", "got"],
    books: ["agot", "twoiaf"],
    parents: [],
    spouses: ["cassana_baratheon"],
    note: "Father of Robert, Stannis, and Renly."
  },
  {
    id: "cassana_baratheon",
    name: "Cassana Estermont",
    house: "other",
    x: 1415,
    y: 1425,
    media: ["books"],
    books: ["twoiaf"],
    parents: [],
    spouses: ["steffon_baratheon"],
    note: "Mother of the Baratheon brothers."
  },
  {
    id: "robert_baratheon",
    name: "Robert Baratheon",
    house: "baratheon",
    x: 1155,
    y: 1535,
    media: ["books", "got"],
    books: ["agot"],
    parents: ["steffon_baratheon", "cassana_baratheon"],
    spouses: ["cersei_lannister"],
    note: "Overthrew Aerys II and sat the Iron Throne."
  },
  {
    id: "stannis_baratheon",
    name: "Stannis Baratheon",
    house: "baratheon",
    x: 1325,
    y: 1535,
    media: ["books", "got"],
    books: ["acok", "asos", "adwd"],
    parents: ["steffon_baratheon", "cassana_baratheon"],
    spouses: [],
    note: "Robert's brother and lawful claimant by strict succession."
  },
  {
    id: "renly_baratheon",
    name: "Renly Baratheon",
    house: "baratheon",
    x: 1495,
    y: 1535,
    media: ["books", "got"],
    books: ["agot", "acok"],
    parents: ["steffon_baratheon", "cassana_baratheon"],
    spouses: [],
    note: "Youngest Baratheon brother and rival claimant."
  },
  {
    id: "shireen_baratheon",
    name: "Shireen Baratheon",
    house: "baratheon",
    x: 1325,
    y: 1755,
    media: ["books", "got"],
    books: ["acok", "asos", "adwd"],
    parents: ["stannis_baratheon"],
    spouses: [],
    note: "Stannis's daughter."
  },
  {
    id: "gendry",
    name: "Gendry",
    house: "baratheon",
    x: 1125,
    y: 1755,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "affc"],
    parents: ["robert_baratheon"],
    spouses: [],
    note: "Robert's son, acknowledged as Baratheon in the show."
  },
  {
    id: "tywin_lannister",
    name: "Tywin Lannister",
    house: "lannister",
    x: 1505,
    y: 1310,
    media: ["books", "got"],
    books: ["agot", "acok", "asos"],
    parents: [],
    spouses: ["joanna_lannister"],
    note: "Lord of Casterly Rock and architect of Lannister power."
  },
  {
    id: "joanna_lannister",
    name: "Joanna Lannister",
    house: "lannister",
    x: 1645,
    y: 1310,
    media: ["books", "got"],
    books: ["agot"],
    parents: [],
    spouses: ["tywin_lannister"],
    note: "Mother of Cersei, Jaime, and Tyrion."
  },
  {
    id: "cersei_lannister",
    name: "Cersei Lannister",
    house: "lannister",
    x: 1510,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "affc", "adwd"],
    parents: ["tywin_lannister", "joanna_lannister"],
    spouses: ["robert_baratheon"],
    note: "Queen to Robert, then show ruler after Tommen."
  },
  {
    id: "jaime_lannister",
    name: "Jaime Lannister",
    house: "lannister",
    x: 1645,
    y: 1535,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "affc", "adwd"],
    parents: ["tywin_lannister", "joanna_lannister"],
    spouses: [],
    note: "Kingslayer and secret father of Cersei's children."
  },
  {
    id: "tyrion_lannister",
    name: "Tyrion Lannister",
    house: "lannister",
    x: 1645,
    y: 1645,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "adwd"],
    parents: ["tywin_lannister", "joanna_lannister"],
    spouses: [],
    note: "Lannister exile and political strategist."
  },
  {
    id: "joffrey_baratheon",
    name: "Joffrey Baratheon",
    house: "baratheon",
    x: 1450,
    y: 1755,
    media: ["books", "got"],
    books: ["agot", "acok", "asos"],
    parents: ["cersei_lannister", "jaime_lannister"],
    legalParents: ["robert_baratheon"],
    spouses: [],
    note: "Legally Robert's heir; biologically Jaime and Cersei's son."
  },
  {
    id: "myrcella_baratheon",
    name: "Myrcella Baratheon",
    house: "baratheon",
    x: 1605,
    y: 1755,
    media: ["books", "got"],
    books: ["agot", "acok", "affc", "adwd"],
    parents: ["cersei_lannister", "jaime_lannister"],
    legalParents: ["robert_baratheon"],
    spouses: [],
    note: "Princess sent to Dorne."
  },
  {
    id: "tommen_baratheon",
    name: "Tommen Baratheon",
    house: "baratheon",
    x: 1530,
    y: 1865,
    media: ["books", "got"],
    books: ["agot", "acok", "asos", "affc", "adwd"],
    parents: ["cersei_lannister", "jaime_lannister"],
    legalParents: ["robert_baratheon"],
    spouses: [],
    note: "Young king after Joffrey."
  }
];

export const EXTRA_LINKS = [
  {
    source: "duncan_tall",
    target: "aegon_v",
    type: "sworn",
    label: "sworn companions"
  }
];

export const THRONE = [
  { id: "aegon_i", ruler: "Aegon I", years: "1-37 AC", status: "confirmed", note: "Conquest and foundation" },
  { id: "aenys_i", ruler: "Aenys I", years: "37-42 AC", status: "confirmed", note: "Inherited from Aegon I" },
  { id: "maegor_i", ruler: "Maegor I", years: "42-48 AC", status: "confirmed", note: "Usurped amid civil war" },
  { id: "jaehaerys_i", ruler: "Jaehaerys I", years: "48-103 AC", status: "confirmed", note: "Long peace after Maegor" },
  { id: "viserys_i", ruler: "Viserys I", years: "103-129 AC", status: "confirmed", note: "His succession set up the Dance" },
  { id: "aegon_ii", ruler: "Aegon II", years: "129-131 AC", status: "contested", note: "Crowned against Rhaenyra" },
  { id: "rhaenyra", ruler: "Rhaenyra", years: "129-130 AC", status: "contested", note: "Claimed and briefly held King's Landing" },
  { id: "aegon_iii", ruler: "Aegon III", years: "131-157 AC", status: "confirmed", note: "Post-Dance king" },
  { id: "daeron_i", ruler: "Daeron I", years: "157-161 AC", status: "confirmed", note: "The Young Dragon" },
  { id: "baelor_i", ruler: "Baelor I", years: "161-171 AC", status: "confirmed", note: "The Blessed" },
  { id: "viserys_ii", ruler: "Viserys II", years: "171-172 AC", status: "confirmed", note: "Brief but able reign" },
  { id: "aegon_iv", ruler: "Aegon IV", years: "172-184 AC", status: "confirmed", note: "The Unworthy" },
  { id: "daeron_ii", ruler: "Daeron II", years: "184-209 AC", status: "confirmed", note: "Dorne joins the realm" },
  { id: "aerys_i", ruler: "Aerys I", years: "209-221 AC", status: "confirmed", note: "Dunk and Egg era" },
  { id: "maekar_i", ruler: "Maekar I", years: "221-233 AC", status: "confirmed", note: "Father of Egg" },
  { id: "aegon_v", ruler: "Aegon V", years: "233-259 AC", status: "confirmed", note: "Egg becomes king" },
  { id: "jaehaerys_ii", ruler: "Jaehaerys II", years: "259-262 AC", status: "confirmed", note: "Short reign" },
  { id: "aerys_ii", ruler: "Aerys II", years: "262-283 AC", status: "confirmed", note: "Deposed by rebellion" },
  { id: "robert_baratheon", ruler: "Robert I", years: "283-298 AC", status: "confirmed", note: "Baratheon dynasty" },
  { id: "joffrey_baratheon", ruler: "Joffrey I", years: "298-300 AC", status: "contested", note: "Legal heir, disputed bloodline" },
  { id: "tommen_baratheon", ruler: "Tommen I", years: "300 AC", status: "contested", note: "Legal heir, disputed bloodline" },
  { id: "cersei_lannister", ruler: "Cersei I", years: "Show: 303-305 AC", status: "show-only", note: "Show-only queen after Tommen" },
  { id: "daenerys_t", ruler: "Daenerys", years: "Show: 305 AC", status: "show-only", note: "Took King's Landing; throne destroyed soon after" },
  { id: "bran_stark", ruler: "Bran I", years: "Show: after 305 AC", status: "show-only", note: "Elected king of six kingdoms, not the Iron Throne" }
];
