// Generated by scripts/sync-portraits.mjs. Edit that script for aliases or source policy changes.
export const PORTRAITS = {
  "aegon_i": {
    "image": "./assets/portraits/sourced/aegon_i.webp",
    "fallback": "./assets/portraits/generated/aegon_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_I_Targaryen",
    "pageTitle": "Aegon I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; United six kingdoms and forged the Iron Throne."
  },
  "rhaenys_t": {
    "image": "./assets/portraits/sourced/rhaenys_t.webp",
    "fallback": "./assets/portraits/generated/rhaenys_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaenys_Targaryen",
    "pageTitle": "Rhaenys Targaryen",
    "generatedTraits": "Valyrian queen with silver-gold hair, violet eyes, fine features, and a calm conqueror's bearing."
  },
  "visenya_t": {
    "image": "./assets/portraits/sourced/visenya_t.webp",
    "fallback": "./assets/portraits/generated/visenya_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Visenya_Targaryen",
    "pageTitle": "Visenya Targaryen",
    "generatedTraits": "Stern Valyrian warrior queen with silver-gold hair, violet eyes, severe cheekbones, and dark armor."
  },
  "aenys_i": {
    "image": "./assets/portraits/sourced/aenys_i.webp",
    "fallback": "./assets/portraits/generated/aenys_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aenys_Targaryen",
    "pageTitle": "Aenys Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Second king on the Iron Throne."
  },
  "maegor_i": {
    "image": "./assets/portraits/sourced/maegor_i.webp",
    "fallback": "./assets/portraits/generated/maegor_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Maegor_Targaryen",
    "pageTitle": "Maegor Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Usurped his nephew's claim and ruled through terror."
  },
  "jaehaerys_i": {
    "image": "./assets/portraits/sourced/jaehaerys_i.webp",
    "fallback": "./assets/portraits/generated/jaehaerys_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jaehaerys_I_Targaryen",
    "pageTitle": "Jaehaerys I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; His long reign shaped the realm and the succession crisis that followed."
  },
  "alysanne_t": {
    "image": "./assets/portraits/sourced/alysanne_t.webp",
    "fallback": "./assets/portraits/generated/alysanne_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Alysanne_Targaryen",
    "pageTitle": "Alysanne Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Jaehaerys's sister-wife and a decisive queen in her own right."
  },
  "aemon_prince": {
    "image": "./assets/portraits/generated/aemon_prince.webp",
    "fallback": "./assets/portraits/generated/aemon_prince.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Valyrian crown prince with silver hair, violet eyes, aquiline features, and restrained dragonrider armor."
  },
  "baelon_prince": {
    "image": "./assets/portraits/sourced/baelon_prince.webp",
    "fallback": "./assets/portraits/generated/baelon_prince.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Baelon_Targaryen",
    "pageTitle": "Baelon Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Father of Viserys I and Daemon."
  },
  "alyssa_t": {
    "image": "./assets/portraits/sourced/alyssa_t.webp",
    "fallback": "./assets/portraits/generated/alyssa_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Alyssa_Targaryen",
    "pageTitle": "Alyssa Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Mother of Viserys I and Daemon."
  },
  "jocelyn_baratheon": {
    "image": "./assets/portraits/generated/jocelyn_baratheon.webp",
    "fallback": "./assets/portraits/generated/jocelyn_baratheon.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Black-haired Baratheon noblewoman with strong stormland features, blue eyes, and formal court dress."
  },
  "rhaenys_queen": {
    "image": "./assets/portraits/sourced/rhaenys_queen.webp",
    "fallback": "./assets/portraits/generated/rhaenys_queen.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaenys_Targaryen_(daughter_of_Aemon)",
    "pageTitle": "Rhaenys Targaryen (daughter of Aemon)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Passed over by the Great Council, later a major power in the Dance."
  },
  "corlys_velaryon": {
    "image": "./assets/portraits/sourced/corlys_velaryon.webp",
    "fallback": "./assets/portraits/generated/corlys_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Corlys_Velaryon",
    "pageTitle": "Corlys Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Lord of the tides and patriarch of a dragonriding Velaryon branch."
  },
  "viserys_i": {
    "image": "./assets/portraits/sourced/viserys_i.webp",
    "fallback": "./assets/portraits/generated/viserys_i.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Viserys_I_Targaryen",
    "pageTitle": "Viserys I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Named Rhaenyra heir, but his second marriage produced rival claimants."
  },
  "daemon_t": {
    "image": "./assets/portraits/sourced/daemon_t.webp",
    "fallback": "./assets/portraits/generated/daemon_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daemon_Targaryen",
    "pageTitle": "Daemon Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Brother to Viserys I and husband to Rhaenyra."
  },
  "aemma_arryn": {
    "image": "./assets/portraits/sourced/aemma_arryn.webp",
    "fallback": "./assets/portraits/generated/aemma_arryn.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aemma_Arryn",
    "pageTitle": "Aemma Arryn",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Mother of Rhaenyra."
  },
  "alicent_hightower": {
    "image": "./assets/portraits/sourced/alicent_hightower.webp",
    "fallback": "./assets/portraits/generated/alicent_hightower.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Alicent_Hightower",
    "pageTitle": "Alicent Hightower",
    "generatedTraits": "auburn or brown hair, composed oldtown courtly features, green and pale gold clothing; Mother of Aegon II, Helaena, Aemond, and Daeron."
  },
  "laena_velaryon": {
    "image": "./assets/portraits/sourced/laena_velaryon.webp",
    "fallback": "./assets/portraits/generated/laena_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Laena_Velaryon",
    "pageTitle": "Laena Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Daughter of Corlys and Rhaenys; Daemon's second wife."
  },
  "laenor_velaryon": {
    "image": "./assets/portraits/sourced/laenor_velaryon.webp",
    "fallback": "./assets/portraits/generated/laenor_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Laenor_Velaryon",
    "pageTitle": "Laenor Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Rhaenyra's first husband and legal father of her elder sons."
  },
  "rhaenyra": {
    "image": "./assets/portraits/sourced/rhaenyra.webp",
    "fallback": "./assets/portraits/generated/rhaenyra.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaenyra_Targaryen",
    "pageTitle": "Rhaenyra Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Named heir to Viserys I; claimant and brief ruler in the Dance."
  },
  "aegon_ii": {
    "image": "./assets/portraits/sourced/aegon_ii.webp",
    "fallback": "./assets/portraits/generated/aegon_ii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_II_Targaryen",
    "pageTitle": "Aegon II Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Crowned against Rhaenyra, making the Dance inevitable."
  },
  "helaena_t": {
    "image": "./assets/portraits/sourced/helaena_t.webp",
    "fallback": "./assets/portraits/generated/helaena_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Helaena_Targaryen",
    "pageTitle": "Helaena Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Sister-wife to Aegon II."
  },
  "aemond_t": {
    "image": "./assets/portraits/sourced/aemond_t.webp",
    "fallback": "./assets/portraits/generated/aemond_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aemond_Targaryen",
    "pageTitle": "Aemond Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; A major Green prince and dragonrider."
  },
  "daeron_daring": {
    "image": "./assets/portraits/sourced/daeron_daring.webp",
    "fallback": "./assets/portraits/generated/daeron_daring.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daeron_Targaryen",
    "pageTitle": "Daeron Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Youngest son of Viserys I and Alicent."
  },
  "jacaerys": {
    "image": "./assets/portraits/sourced/jacaerys.webp",
    "fallback": "./assets/portraits/generated/jacaerys.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jacaerys_Velaryon",
    "pageTitle": "Jacaerys Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Rhaenyra's eldest son and heir during the Dance."
  },
  "lucerys": {
    "image": "./assets/portraits/sourced/lucerys.webp",
    "fallback": "./assets/portraits/generated/lucerys.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Lucerys_Velaryon",
    "pageTitle": "Lucerys Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; His mission to Storm's End becomes a turning point."
  },
  "joffrey_velaryon": {
    "image": "./assets/portraits/sourced/joffrey_velaryon.webp",
    "fallback": "./assets/portraits/generated/joffrey_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Joffrey_Velaryon",
    "pageTitle": "Joffrey Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Rhaenyra's third Velaryon son."
  },
  "aegon_iii": {
    "image": "./assets/portraits/sourced/aegon_iii.webp",
    "fallback": "./assets/portraits/generated/aegon_iii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_Targaryen_(son_of_Rhaenyra)",
    "pageTitle": "Aegon Targaryen (son of Rhaenyra)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Survived the Dance and inherited a broken dynasty."
  },
  "viserys_ii": {
    "image": "./assets/portraits/sourced/viserys_ii.webp",
    "fallback": "./assets/portraits/generated/viserys_ii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Viserys_Targaryen_(son_of_Rhaenyra)",
    "pageTitle": "Viserys Targaryen (son of Rhaenyra)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Younger son of Daemon and Rhaenyra; later king."
  },
  "daeron_i": {
    "image": "./assets/portraits/sourced/daeron_i.webp",
    "fallback": "./assets/portraits/generated/daeron_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daeron_I_Targaryen",
    "pageTitle": "Daeron I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Conquered Dorne, briefly."
  },
  "baelor_i": {
    "image": "./assets/portraits/sourced/baelor_i.webp",
    "fallback": "./assets/portraits/generated/baelor_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Baelor_I_Targaryen",
    "pageTitle": "Baelor I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; A pious king whose reign reshaped royal politics."
  },
  "daena_t": {
    "image": "./assets/portraits/sourced/daena_t.webp",
    "fallback": "./assets/portraits/generated/daena_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daena_Targaryen",
    "pageTitle": "Daena Targaryen",
    "generatedTraits": "Defiant Valyrian princess with silver-gold hair, violet eyes, athletic bearing, and a bold red-black gown."
  },
  "aegon_iv": {
    "image": "./assets/portraits/sourced/aegon_iv.webp",
    "fallback": "./assets/portraits/generated/aegon_iv.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_IV_Targaryen",
    "pageTitle": "Aegon IV Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; His legitimized bastards seeded the Blackfyre rebellions."
  },
  "naerys_t": {
    "image": "./assets/portraits/sourced/naerys_t.webp",
    "fallback": "./assets/portraits/generated/naerys_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Naerys_Targaryen",
    "pageTitle": "Naerys Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Sister-wife to Aegon IV and mother of Daeron II."
  },
  "aemon_dragonknight": {
    "image": "./assets/portraits/sourced/aemon_dragonknight.webp",
    "fallback": "./assets/portraits/generated/aemon_dragonknight.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aemon_Targaryen_(son_of_Viserys_II)",
    "pageTitle": "Aemon Targaryen (son of Viserys II)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Legendary Kingsguard knight."
  },
  "daemon_blackfyre": {
    "image": "./assets/portraits/sourced/daemon_blackfyre.webp",
    "fallback": "./assets/portraits/generated/daemon_blackfyre.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daemon_Blackfyre",
    "pageTitle": "Daemon Blackfyre",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Great bastard whose claim split the realm."
  },
  "daeron_ii": {
    "image": "./assets/portraits/sourced/daeron_ii.webp",
    "fallback": "./assets/portraits/generated/daeron_ii.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daeron_II_Targaryen",
    "pageTitle": "Daeron II Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Brought Dorne into the realm by marriage."
  },
  "baelor_breakspear": {
    "image": "./assets/portraits/sourced/baelor_breakspear.webp",
    "fallback": "./assets/portraits/generated/baelor_breakspear.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Baelor_Targaryen",
    "pageTitle": "Baelor Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Prince of Dragonstone and champion at Ashford."
  },
  "aerys_i": {
    "image": "./assets/portraits/sourced/aerys_i.webp",
    "fallback": "./assets/portraits/generated/aerys_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aerys_Targaryen_(son_of_Daeron_II)",
    "pageTitle": "Aerys Targaryen (son of Daeron II)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; King during Dunk and Egg's early wanderings."
  },
  "maekar_i": {
    "image": "./assets/portraits/sourced/maekar_i.webp",
    "fallback": "./assets/portraits/generated/maekar_i.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Maekar_Targaryen",
    "pageTitle": "Maekar Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Father of Egg and later king."
  },
  "aerion_brightflame": {
    "image": "./assets/portraits/sourced/aerion_brightflame.webp",
    "fallback": "./assets/portraits/generated/aerion_brightflame.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aerion_Targaryen",
    "pageTitle": "Aerion Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Maekar's volatile son."
  },
  "aegon_v": {
    "image": "./assets/portraits/sourced/aegon_v.webp",
    "fallback": "./assets/portraits/generated/aegon_v.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_Targaryen",
    "pageTitle": "Aegon Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Dunk's squire, later king and ancestor of Daenerys and Jon."
  },
  "betha_blackwood": {
    "image": "./assets/portraits/generated/betha_blackwood.webp",
    "fallback": "./assets/portraits/generated/betha_blackwood.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Riverlands queen with dark hair, thoughtful brown eyes, and raven-feather Blackwood-inspired embroidery."
  },
  "duncan_tall": {
    "image": "./assets/portraits/sourced/duncan_tall.webp",
    "fallback": "./assets/portraits/generated/duncan_tall.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Duncan_the_Tall",
    "pageTitle": "Duncan the Tall",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Hedge knight, Egg's sworn companion, and future Lord Commander."
  },
  "jaehaerys_ii": {
    "image": "./assets/portraits/generated/jaehaerys_ii.webp",
    "fallback": "./assets/portraits/generated/jaehaerys_ii.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "A slight Valyrian king with silver hair, pale violet eyes, fine tired features, and a sober black-red doublet."
  },
  "aerys_ii": {
    "image": "./assets/portraits/sourced/aerys_ii.webp",
    "fallback": "./assets/portraits/generated/aerys_ii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aerys_II_Targaryen",
    "pageTitle": "Aerys II Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Last Targaryen king before Robert's Rebellion."
  },
  "rhaella_t": {
    "image": "./assets/portraits/sourced/rhaella_t.webp",
    "fallback": "./assets/portraits/generated/rhaella_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaella_Targaryen",
    "pageTitle": "Rhaella Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Mother of Rhaegar, Viserys, and Daenerys."
  },
  "rhaegar_t": {
    "image": "./assets/portraits/sourced/rhaegar_t.webp",
    "fallback": "./assets/portraits/generated/rhaegar_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaegar_Targaryen",
    "pageTitle": "Rhaegar Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Prince whose choices ignited the rebellion and Jon's hidden lineage."
  },
  "elia_martell": {
    "image": "./assets/portraits/sourced/elia_martell.webp",
    "fallback": "./assets/portraits/generated/elia_martell.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Elia_Martell",
    "pageTitle": "Elia Martell",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Princess of Dorne and Rhaegar's wife."
  },
  "viserys_beggar": {
    "image": "./assets/portraits/sourced/viserys_beggar.webp",
    "fallback": "./assets/portraits/generated/viserys_beggar.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Viserys_Targaryen_(son_of_Aerys_II)",
    "pageTitle": "Viserys Targaryen (son of Aerys II)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Exiled claimant before Daenerys rises."
  },
  "daenerys_t": {
    "image": "./assets/portraits/sourced/daenerys_t.webp",
    "fallback": "./assets/portraits/generated/daenerys_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daenerys_Targaryen",
    "pageTitle": "Daenerys Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Dragon queen and last public Targaryen claimant in the show era."
  },
  "rickard_stark": {
    "image": "./assets/portraits/sourced/rickard_stark.webp",
    "fallback": "./assets/portraits/generated/rickard_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rickard_Stark",
    "pageTitle": "Rickard Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Lord of Winterfell before Robert's Rebellion."
  },
  "lyarra_stark": {
    "image": "./assets/portraits/generated/lyarra_stark.webp",
    "fallback": "./assets/portraits/generated/lyarra_stark.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Northern noblewoman with long brown hair, grey eyes, pale winter complexion, and quiet Stark dignity."
  },
  "brandon_stark_uncle": {
    "image": "./assets/portraits/sourced/brandon_stark_uncle.webp",
    "fallback": "./assets/portraits/generated/brandon_stark_uncle.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Brandon_Stark",
    "pageTitle": "Brandon Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Eddard's elder brother, killed by Aerys II."
  },
  "eddard_stark": {
    "image": "./assets/portraits/sourced/eddard_stark.webp",
    "fallback": "./assets/portraits/generated/eddard_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Eddard_Stark",
    "pageTitle": "Eddard Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Lord of Winterfell and Jon's public father."
  },
  "lyanna_stark": {
    "image": "./assets/portraits/sourced/lyanna_stark.webp",
    "fallback": "./assets/portraits/generated/lyanna_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Lyanna_Stark",
    "pageTitle": "Lyanna Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Jon's mother and the hidden Stark-Targaryen bridge."
  },
  "benjen_stark": {
    "image": "./assets/portraits/sourced/benjen_stark.webp",
    "fallback": "./assets/portraits/generated/benjen_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Benjen_Stark",
    "pageTitle": "Benjen Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Night's Watch ranger and Eddard's brother."
  },
  "catelyn_stark": {
    "image": "./assets/portraits/sourced/catelyn_stark.webp",
    "fallback": "./assets/portraits/generated/catelyn_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Catelyn_Stark",
    "pageTitle": "Catelyn Stark",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Born Tully, Lady of Winterfell."
  },
  "robb_stark": {
    "image": "./assets/portraits/sourced/robb_stark.webp",
    "fallback": "./assets/portraits/generated/robb_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Robb_Stark",
    "pageTitle": "Robb Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; King in the North during the War of the Five Kings."
  },
  "sansa_stark": {
    "image": "./assets/portraits/sourced/sansa_stark.webp",
    "fallback": "./assets/portraits/generated/sansa_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Sansa_Stark",
    "pageTitle": "Sansa Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Political survivor and Queen in the North in the show ending."
  },
  "arya_stark": {
    "image": "./assets/portraits/sourced/arya_stark.webp",
    "fallback": "./assets/portraits/generated/arya_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Arya_Stark",
    "pageTitle": "Arya Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Faceless-trained Stark daughter."
  },
  "bran_stark": {
    "image": "./assets/portraits/sourced/bran_stark.webp",
    "fallback": "./assets/portraits/generated/bran_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Bran_Stark",
    "pageTitle": "Bran Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Chosen king of the Six Kingdoms in the show after the Iron Throne is destroyed."
  },
  "rickon_stark": {
    "image": "./assets/portraits/sourced/rickon_stark.webp",
    "fallback": "./assets/portraits/generated/rickon_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rickon_Stark",
    "pageTitle": "Rickon Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Youngest Stark child."
  },
  "jon_snow": {
    "image": "./assets/portraits/sourced/jon_snow.webp",
    "fallback": "./assets/portraits/generated/jon_snow.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jon_Snow",
    "pageTitle": "Jon Snow",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Raised as Ned's bastard; show canon reveals Rhaegar and Lyanna as parents."
  },
  "steffon_baratheon": {
    "image": "./assets/portraits/sourced/steffon_baratheon.webp",
    "fallback": "./assets/portraits/generated/steffon_baratheon.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Steffon_Baratheon",
    "pageTitle": "Steffon Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Father of Robert, Stannis, and Renly."
  },
  "cassana_baratheon": {
    "image": "./assets/portraits/generated/cassana_baratheon.webp",
    "fallback": "./assets/portraits/generated/cassana_baratheon.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Stormlands lady with chestnut hair, clear eyes, and dignified green-and-gold Estermont court dress."
  },
  "robert_baratheon": {
    "image": "./assets/portraits/sourced/robert_baratheon.webp",
    "fallback": "./assets/portraits/generated/robert_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Robert_Baratheon",
    "pageTitle": "Robert Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Overthrew Aerys II and sat the Iron Throne."
  },
  "stannis_baratheon": {
    "image": "./assets/portraits/sourced/stannis_baratheon.webp",
    "fallback": "./assets/portraits/generated/stannis_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Stannis_Baratheon",
    "pageTitle": "Stannis Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Robert's brother and lawful claimant by strict succession."
  },
  "renly_baratheon": {
    "image": "./assets/portraits/sourced/renly_baratheon.webp",
    "fallback": "./assets/portraits/generated/renly_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Renly_Baratheon",
    "pageTitle": "Renly Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Youngest Baratheon brother and rival claimant."
  },
  "shireen_baratheon": {
    "image": "./assets/portraits/sourced/shireen_baratheon.webp",
    "fallback": "./assets/portraits/generated/shireen_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Shireen_Baratheon",
    "pageTitle": "Shireen Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Stannis's daughter."
  },
  "gendry": {
    "image": "./assets/portraits/sourced/gendry.webp",
    "fallback": "./assets/portraits/generated/gendry.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Gendry_Baratheon",
    "pageTitle": "Gendry Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Robert's son, acknowledged as Baratheon in the show."
  },
  "tywin_lannister": {
    "image": "./assets/portraits/sourced/tywin_lannister.webp",
    "fallback": "./assets/portraits/generated/tywin_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Tywin_Lannister",
    "pageTitle": "Tywin Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Lord of Casterly Rock and architect of Lannister power."
  },
  "joanna_lannister": {
    "image": "./assets/portraits/generated/joanna_lannister.webp",
    "fallback": "./assets/portraits/generated/joanna_lannister.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Golden-haired Lannister noblewoman with green eyes, elegant poise, and crimson-and-gold court dress."
  },
  "cersei_lannister": {
    "image": "./assets/portraits/sourced/cersei_lannister.webp",
    "fallback": "./assets/portraits/generated/cersei_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Cersei_Lannister",
    "pageTitle": "Cersei Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Queen to Robert, then show ruler after Tommen."
  },
  "jaime_lannister": {
    "image": "./assets/portraits/sourced/jaime_lannister.webp",
    "fallback": "./assets/portraits/generated/jaime_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jaime_Lannister",
    "pageTitle": "Jaime Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Kingslayer and secret father of Cersei's children."
  },
  "tyrion_lannister": {
    "image": "./assets/portraits/sourced/tyrion_lannister.webp",
    "fallback": "./assets/portraits/generated/tyrion_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Tyrion_Lannister",
    "pageTitle": "Tyrion Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Lannister exile and political strategist."
  },
  "joffrey_baratheon": {
    "image": "./assets/portraits/sourced/joffrey_baratheon.webp",
    "fallback": "./assets/portraits/generated/joffrey_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Joffrey_Baratheon",
    "pageTitle": "Joffrey Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Legally Robert's heir; biologically Jaime and Cersei's son."
  },
  "myrcella_baratheon": {
    "image": "./assets/portraits/sourced/myrcella_baratheon.webp",
    "fallback": "./assets/portraits/generated/myrcella_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Myrcella_Baratheon",
    "pageTitle": "Myrcella Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Princess sent to Dorne."
  },
  "tommen_baratheon": {
    "image": "./assets/portraits/sourced/tommen_baratheon.webp",
    "fallback": "./assets/portraits/generated/tommen_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Tommen_Baratheon",
    "pageTitle": "Tommen Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Young king after Joffrey."
  }
};
