// Generated by scripts/sync-portraits.mjs. Edit that script for aliases or source policy changes.
export const PORTRAITS = {
  "aegon_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/41/Aegon_the_Conqueror.png/revision/latest/scale-to-width-down/433?cb=20171215014730",
    "fallback": "./assets/portraits/generated/aegon_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_I_Targaryen",
    "pageTitle": "Aegon I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; United six kingdoms and forged the Iron Throne."
  },
  "rhaenys_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/2/21/Rhaenys_Targaryen1.png/revision/latest?cb=20171006180009",
    "fallback": "./assets/portraits/generated/rhaenys_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaenys_Targaryen",
    "pageTitle": "Rhaenys Targaryen",
    "generatedTraits": "Valyrian queen with silver-gold hair, violet eyes, fine features, and a calm conqueror's bearing."
  },
  "visenya_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/3a/Visenya_Targaryen1.png/revision/latest?cb=20171006173948",
    "fallback": "./assets/portraits/generated/visenya_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Visenya_Targaryen",
    "pageTitle": "Visenya Targaryen",
    "generatedTraits": "Stern Valyrian warrior queen with silver-gold hair, violet eyes, severe cheekbones, and dark armor."
  },
  "aenys_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/7/76/Aenys_I_Targaryen.png/revision/latest?cb=20160313083909",
    "fallback": "./assets/portraits/generated/aenys_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aenys_Targaryen",
    "pageTitle": "Aenys Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Second king on the Iron Throne."
  },
  "maegor_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/42/HL5_Maegor_headshot.png/revision/latest/scale-to-width-down/386?cb=20170219034237",
    "fallback": "./assets/portraits/generated/maegor_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Maegor_Targaryen",
    "pageTitle": "Maegor Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Usurped his nephew's claim and ruled through terror."
  },
  "jaehaerys_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/2/22/Jaehaerys_I_Targaryen_Official_Guide.jpg/revision/latest/scale-to-width-down/340?cb=20220823075450",
    "fallback": "./assets/portraits/generated/jaehaerys_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jaehaerys_I_Targaryen",
    "pageTitle": "Jaehaerys I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; His long reign shaped the realm and the succession crisis that followed."
  },
  "alysanne_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/6/67/Alysanne_Targaryen.png/revision/latest/scale-to-width-down/257?cb=20240618073808",
    "fallback": "./assets/portraits/generated/alysanne_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Alysanne_Targaryen",
    "pageTitle": "Alysanne Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Jaehaerys's sister-wife and a decisive queen in her own right."
  },
  "aemon_prince": {
    "image": "./assets/portraits/generated/aemon_prince.webp",
    "fallback": "./assets/portraits/generated/aemon_prince.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Valyrian crown prince with silver hair, violet eyes, aquiline features, and restrained dragonrider armor."
  },
  "baelon_prince": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/5b/Baelon_Targaryen.png/revision/latest/scale-to-width-down/500?cb=20220823104607",
    "fallback": "./assets/portraits/generated/baelon_prince.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Baelon_Targaryen",
    "pageTitle": "Baelon Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Father of Viserys I and Daemon."
  },
  "alyssa_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/39/AlyssaTargaryen2.jpeg/revision/latest/scale-to-width-down/405?cb=20240717093158",
    "fallback": "./assets/portraits/generated/alyssa_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Alyssa_Targaryen",
    "pageTitle": "Alyssa Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Mother of Viserys I and Daemon."
  },
  "jocelyn_baratheon": {
    "image": "./assets/portraits/generated/jocelyn_baratheon.webp",
    "fallback": "./assets/portraits/generated/jocelyn_baratheon.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Black-haired Baratheon noblewoman with strong stormland features, blue eyes, and formal court dress."
  },
  "rhaenys_queen": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/39/S2_Rhaenys_Targaryen_Infobox.jpg/revision/latest/scale-to-width-down/393?cb=20240708102159",
    "fallback": "./assets/portraits/generated/rhaenys_queen.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaenys_Targaryen_(daughter_of_Aemon)",
    "pageTitle": "Rhaenys Targaryen (daughter of Aemon)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Passed over by the Great Council, later a major power in the Dance."
  },
  "corlys_velaryon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/5a/Corlys_Velaryon_S2.jpg/revision/latest/scale-to-width-down/333?cb=20240606091353",
    "fallback": "./assets/portraits/generated/corlys_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Corlys_Velaryon",
    "pageTitle": "Corlys Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Lord of the tides and patriarch of a dragonriding Velaryon branch."
  },
  "viserys_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/38/Viserys_I_Targaryen_Official_Guide.jpg/revision/latest/scale-to-width-down/340?cb=20220826232345",
    "fallback": "./assets/portraits/generated/viserys_i.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Viserys_I_Targaryen",
    "pageTitle": "Viserys I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Named Rhaenyra heir, but his second marriage produced rival claimants."
  },
  "daemon_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/d/d5/Daemon_S3_Profile.png/revision/latest/scale-to-width-down/340?cb=20260625083415",
    "fallback": "./assets/portraits/generated/daemon_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daemon_Targaryen",
    "pageTitle": "Daemon Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Brother to Viserys I and husband to Rhaenyra."
  },
  "aemma_arryn": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/2/28/Aemma_Arryn_Official_Guide.jpg/revision/latest/scale-to-width-down/340?cb=20220823094427",
    "fallback": "./assets/portraits/generated/aemma_arryn.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aemma_Arryn",
    "pageTitle": "Aemma Arryn",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Mother of Rhaenyra."
  },
  "alicent_hightower": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/1/18/AlicentASfASInfobox.PNG/revision/latest/scale-to-width-down/351?cb=20240621112258",
    "fallback": "./assets/portraits/generated/alicent_hightower.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Alicent_Hightower",
    "pageTitle": "Alicent Hightower",
    "generatedTraits": "auburn or brown hair, composed oldtown courtly features, green and pale gold clothing; Mother of Aegon II, Helaena, Aemond, and Daeron."
  },
  "laena_velaryon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/a/ab/Laena_Velaryon_Official_Guide_3.jpg/revision/latest/scale-to-width-down/340?cb=20220926034616",
    "fallback": "./assets/portraits/generated/laena_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Laena_Velaryon",
    "pageTitle": "Laena Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Daughter of Corlys and Rhaenys; Daemon's second wife."
  },
  "laenor_velaryon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/50/Laenor_Velaryon_Official_Guide_3.jpg/revision/latest/scale-to-width-down/340?cb=20220926034629",
    "fallback": "./assets/portraits/generated/laenor_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Laenor_Velaryon",
    "pageTitle": "Laenor Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Rhaenyra's first husband and legal father of her elder sons."
  },
  "rhaenyra": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/5f/Queen_Rhaenyra.jpg/revision/latest/scale-to-width-down/352?cb=20221024065800",
    "fallback": "./assets/portraits/generated/rhaenyra.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaenyra_Targaryen",
    "pageTitle": "Rhaenyra Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Named heir to Viserys I; claimant and brief ruler in the Dance."
  },
  "aegon_ii": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/a/a1/AegonII-S3-Profile.png/revision/latest/scale-to-width-down/360?cb=20260522073705",
    "fallback": "./assets/portraits/generated/aegon_ii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_II_Targaryen",
    "pageTitle": "Aegon II Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Crowned against Rhaenyra, making the Dance inevitable."
  },
  "helaena_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/6/60/HelaenaASfASInfobox.PNG/revision/latest/scale-to-width-down/357?cb=20240621111347",
    "fallback": "./assets/portraits/generated/helaena_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Helaena_Targaryen",
    "pageTitle": "Helaena Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Sister-wife to Aegon II."
  },
  "aemond_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/4f/Aemond_Targaryen_S2.jpg/revision/latest/scale-to-width-down/380?cb=20240606091326",
    "fallback": "./assets/portraits/generated/aemond_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aemond_Targaryen",
    "pageTitle": "Aemond Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; A major Green prince and dragonrider."
  },
  "daeron_daring": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/1/1c/Daeron_on_Tessarion.png/revision/latest/scale-to-width-down/471?cb=20240806073456",
    "fallback": "./assets/portraits/generated/daeron_daring.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daeron_Targaryen",
    "pageTitle": "Daeron Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Youngest son of Viserys I and Alicent."
  },
  "jacaerys": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/5f/Jacaerys-206.jpeg/revision/latest/scale-to-width-down/364?cb=20240719110656",
    "fallback": "./assets/portraits/generated/jacaerys.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jacaerys_Velaryon",
    "pageTitle": "Jacaerys Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Rhaenyra's eldest son and heir during the Dance."
  },
  "lucerys": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/32/Lucerys_Velaryon_Official_Guide_2.jpg/revision/latest/scale-to-width-down/340?cb=20221010040909",
    "fallback": "./assets/portraits/generated/lucerys.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Lucerys_Velaryon",
    "pageTitle": "Lucerys Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; His mission to Storm's End becomes a turning point."
  },
  "joffrey_velaryon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/49/Joffrey_Velaryon_HotD.webp/revision/latest/scale-to-width-down/332?cb=20241002030724",
    "fallback": "./assets/portraits/generated/joffrey_velaryon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Joffrey_Velaryon",
    "pageTitle": "Joffrey Velaryon",
    "generatedTraits": "silver or white-blond hair, refined seafaring noble features, sea-blue and silver clothing; Rhaenyra's third Velaryon son."
  },
  "aegon_iii": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/55/Aegon_III_baby.png/revision/latest/scale-to-width-down/366?cb=20221015090043",
    "fallback": "./assets/portraits/generated/aegon_iii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_Targaryen_(son_of_Rhaenyra)",
    "pageTitle": "Aegon Targaryen (son of Rhaenyra)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Survived the Dance and inherited a broken dynasty."
  },
  "viserys_ii": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/0/0e/Viserys_II_baby.png/revision/latest/scale-to-width-down/388?cb=20221015085914",
    "fallback": "./assets/portraits/generated/viserys_ii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Viserys_Targaryen_(son_of_Rhaenyra)",
    "pageTitle": "Viserys Targaryen (son of Rhaenyra)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Younger son of Daemon and Rhaenyra; later king."
  },
  "daeron_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/6/65/Daeron_I_Targaryen_the_Young_Dragon.png/revision/latest/scale-to-width-down/221?cb=20140714015658",
    "fallback": "./assets/portraits/generated/daeron_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daeron_I_Targaryen",
    "pageTitle": "Daeron I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Conquered Dorne, briefly."
  },
  "baelor_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/d/d2/Baelor_the_Blessed.png/revision/latest/scale-to-width-down/391?cb=20161118171335",
    "fallback": "./assets/portraits/generated/baelor_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Baelor_I_Targaryen",
    "pageTitle": "Baelor I Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; A pious king whose reign reshaped royal politics."
  },
  "daena_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/6/68/Daena.png/revision/latest?cb=20140222124100",
    "fallback": "./assets/portraits/generated/daena_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daena_Targaryen",
    "pageTitle": "Daena Targaryen",
    "generatedTraits": "Defiant Valyrian princess with silver-gold hair, violet eyes, athletic bearing, and a bold red-black gown."
  },
  "aegon_iv": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/6/64/Aegon-IV-S8.png/revision/latest/scale-to-width-down/365?cb=20191127140740",
    "fallback": "./assets/portraits/generated/aegon_iv.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_IV_Targaryen",
    "pageTitle": "Aegon IV Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; His legitimized bastards seeded the Blackfyre rebellions."
  },
  "naerys_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/9/91/Queen-Naerys.png/revision/latest/scale-to-width-down/351?cb=20191127141054",
    "fallback": "./assets/portraits/generated/naerys_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Naerys_Targaryen",
    "pageTitle": "Naerys Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Sister-wife to Aegon IV and mother of Daeron II."
  },
  "aemon_dragonknight": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/1/1d/Dragonknight.png/revision/latest/scale-to-width-down/340?cb=20191127141326",
    "fallback": "./assets/portraits/generated/aemon_dragonknight.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aemon_Targaryen_(son_of_Viserys_II)",
    "pageTitle": "Aemon Targaryen (son of Viserys II)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Legendary Kingsguard knight."
  },
  "daemon_blackfyre": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/f/fd/BlackDragon-S8.png/revision/latest/scale-to-width-down/369?cb=20191127142304",
    "fallback": "./assets/portraits/generated/daemon_blackfyre.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daemon_Blackfyre",
    "pageTitle": "Daemon Blackfyre",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Great bastard whose claim split the realm."
  },
  "daeron_ii": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/c/c4/Daeron-S8.png/revision/latest/scale-to-width-down/314?cb=20191127142407",
    "fallback": "./assets/portraits/generated/daeron_ii.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daeron_II_Targaryen",
    "pageTitle": "Daeron II Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Brought Dorne into the realm by marriage."
  },
  "baelor_breakspear": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/b/b5/Baelor_Breakspear-AKotSK.png/revision/latest/scale-to-width-down/406?cb=20260223232300",
    "fallback": "./assets/portraits/generated/baelor_breakspear.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Baelor_Targaryen",
    "pageTitle": "Baelor Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Prince of Dragonstone and champion at Ashford."
  },
  "aerys_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/9/93/Roman_Papsuev_-_Aerys_I_Targaryen.jpg/revision/latest?cb=20230701105804",
    "fallback": "./assets/portraits/generated/aerys_i.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aerys_Targaryen_(son_of_Daeron_II)",
    "pageTitle": "Aerys Targaryen (son of Daeron II)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; King during Dunk and Egg's early wanderings."
  },
  "maekar_i": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/3a/Maekar-Seven.jpg/revision/latest/scale-to-width-down/405?cb=20260204115453",
    "fallback": "./assets/portraits/generated/maekar_i.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Maekar_Targaryen",
    "pageTitle": "Maekar Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Father of Egg and later king."
  },
  "aerion_brightflame": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/b/bd/Aerion-2ndTrailer.png/revision/latest/scale-to-width-down/350?cb=20251226124912",
    "fallback": "./assets/portraits/generated/aerion_brightflame.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aerion_Targaryen",
    "pageTitle": "Aerion Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Maekar's volatile son."
  },
  "aegon_v": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/c/c1/Egg-Promo.png/revision/latest/scale-to-width-down/357?cb=20251227120129",
    "fallback": "./assets/portraits/generated/aegon_v.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aegon_Targaryen",
    "pageTitle": "Aegon Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Dunk's squire, later king and ancestor of Daenerys and Jon."
  },
  "betha_blackwood": {
    "image": "./assets/portraits/generated/betha_blackwood.webp",
    "fallback": "./assets/portraits/generated/betha_blackwood.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Riverlands queen with dark hair, thoughtful brown eyes, and raven-feather Blackwood-inspired embroidery."
  },
  "duncan_tall": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/31/Dunk-The_Morrow.png/revision/latest/scale-to-width-down/375?cb=20260219111850",
    "fallback": "./assets/portraits/generated/duncan_tall.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Duncan_the_Tall",
    "pageTitle": "Duncan the Tall",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Hedge knight, Egg's sworn companion, and future Lord Commander."
  },
  "jaehaerys_ii": {
    "image": "./assets/portraits/generated/jaehaerys_ii.webp",
    "fallback": "./assets/portraits/generated/jaehaerys_ii.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "A slight Valyrian king with silver hair, pale violet eyes, fine tired features, and a sober black-red doublet."
  },
  "aerys_ii": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/47/Aerys_II_Targaryen_Mad_King.jpg/revision/latest/scale-to-width-down/412?cb=20170821102509",
    "fallback": "./assets/portraits/generated/aerys_ii.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Aerys_II_Targaryen",
    "pageTitle": "Aerys II Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Last Targaryen king before Robert's Rebellion."
  },
  "rhaella_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/0/0e/Rhaella_pregnant.png/revision/latest/scale-to-width-down/310?cb=20171216022616",
    "fallback": "./assets/portraits/generated/rhaella_t.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaella_Targaryen",
    "pageTitle": "Rhaella Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Mother of Rhaegar, Viserys, and Daenerys."
  },
  "rhaegar_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/51/Rhaeger_main_infobox.png/revision/latest/scale-to-width-down/306?cb=20210722174123",
    "fallback": "./assets/portraits/generated/rhaegar_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rhaegar_Targaryen",
    "pageTitle": "Rhaegar Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Prince whose choices ignited the rebellion and Jon's hidden lineage."
  },
  "elia_martell": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/c/c6/Elia_Martell.png/revision/latest?cb=20161215025158",
    "fallback": "./assets/portraits/generated/elia_martell.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Elia_Martell",
    "pageTitle": "Elia Martell",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Princess of Dorne and Rhaegar's wife."
  },
  "viserys_beggar": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/46/Viseryspromoheadshot.jpg/revision/latest/scale-to-width-down/392?cb=20210722093457",
    "fallback": "./assets/portraits/generated/viserys_beggar.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Viserys_Targaryen_(son_of_Aerys_II)",
    "pageTitle": "Viserys Targaryen (son of Aerys II)",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Exiled claimant before Daenerys rises."
  },
  "daenerys_t": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/4f/Daenerys_Season_8.jpg/revision/latest/scale-to-width-down/301?cb=20190415212013",
    "fallback": "./assets/portraits/generated/daenerys_t.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Daenerys_Targaryen",
    "pageTitle": "Daenerys Targaryen",
    "generatedTraits": "silver-gold hair, pale skin, violet or lilac eyes, fine Valyrian features, black and muted crimson clothing; Dragon queen and last public Targaryen claimant in the show era."
  },
  "rickard_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/e/eb/Vlcsnap-2016-05-23-02h18m09s851.png/revision/latest?cb=20160523052104",
    "fallback": "./assets/portraits/generated/rickard_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rickard_Stark",
    "pageTitle": "Rickard Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Lord of Winterfell before Robert's Rebellion."
  },
  "lyarra_stark": {
    "image": "./assets/portraits/generated/lyarra_stark.webp",
    "fallback": "./assets/portraits/generated/lyarra_stark.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Northern noblewoman with long brown hair, grey eyes, pale winter complexion, and quiet Stark dignity."
  },
  "brandon_stark_uncle": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/f/f4/BrandonStarkH%26L.png/revision/latest/scale-to-width-down/426?cb=20160227090608",
    "fallback": "./assets/portraits/generated/brandon_stark_uncle.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Brandon_Stark",
    "pageTitle": "Brandon Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Eddard's elder brother, killed by Aerys II."
  },
  "eddard_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/3/34/Eddard_Stark.jpg/revision/latest/scale-to-width-down/357?cb=20190701140812",
    "fallback": "./assets/portraits/generated/eddard_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Eddard_Stark",
    "pageTitle": "Eddard Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Lord of Winterfell and Jon's public father."
  },
  "lyanna_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/8/85/Lyanna_S7_E7.jpg/revision/latest/scale-to-width-down/301?cb=20170830234842",
    "fallback": "./assets/portraits/generated/lyanna_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Lyanna_Stark",
    "pageTitle": "Lyanna Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Jon's mother and the hidden Stark-Targaryen bridge."
  },
  "benjen_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/0/0f/610_Benjen_Promo_Crop.png/revision/latest/scale-to-width-down/391?cb=20160629183134",
    "fallback": "./assets/portraits/generated/benjen_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Benjen_Stark",
    "pageTitle": "Benjen Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Night's Watch ranger and Eddard's brother."
  },
  "catelyn_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/CatelynS3Promo.jpg/revision/latest/scale-to-width-down/303?cb=20190427043743",
    "fallback": "./assets/portraits/generated/catelyn_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Catelyn_Stark",
    "pageTitle": "Catelyn Stark",
    "generatedTraits": "period-accurate Westerosi noble features and clothing based on the character note; Born Tully, Lady of Winterfell."
  },
  "robb_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/50/S3E9_Robb_Stark_main.jpg/revision/latest/scale-to-width-down/327?cb=20160718071203",
    "fallback": "./assets/portraits/generated/robb_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Robb_Stark",
    "pageTitle": "Robb Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; King in the North during the War of the Five Kings."
  },
  "sansa_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/6/63/QueenSansa.PNG/revision/latest?cb=20210215100224",
    "fallback": "./assets/portraits/generated/sansa_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Sansa_Stark",
    "pageTitle": "Sansa Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Political survivor and Queen in the North in the show ending."
  },
  "arya_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/b/be/AryaShipIronThrone.PNG/revision/latest/scale-to-width-down/335?cb=20190520174300",
    "fallback": "./assets/portraits/generated/arya_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Arya_Stark",
    "pageTitle": "Arya Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Faceless-trained Stark daughter."
  },
  "bran_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/8/81/KingBran.PNG/revision/latest/scale-to-width-down/336?cb=20190520173855",
    "fallback": "./assets/portraits/generated/bran_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Bran_Stark",
    "pageTitle": "Bran Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Chosen king of the Six Kingdoms in the show after the Iron Throne is destroyed."
  },
  "rickon_stark": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/d/d9/Battle_of_the_Bastards_42.jpg/revision/latest/scale-to-width-down/365?cb=20160621185459",
    "fallback": "./assets/portraits/generated/rickon_stark.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Rickon_Stark",
    "pageTitle": "Rickon Stark",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Youngest Stark child."
  },
  "jon_snow": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/d/d0/JonSnow8x06.PNG/revision/latest?cb=20190714094440",
    "fallback": "./assets/portraits/generated/jon_snow.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jon_Snow",
    "pageTitle": "Jon Snow",
    "generatedTraits": "brown or dark hair, grey eyes, long northern face, restrained charcoal wool and leather; Raised as Ned's bastard; show canon reveals Rhaegar and Lyanna as parents."
  },
  "steffon_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/a/ad/Steffon_Baratheon.png/revision/latest?cb=20161115175420",
    "fallback": "./assets/portraits/generated/steffon_baratheon.svg",
    "sourceType": "book-art",
    "sourceLabel": "Book / lore illustration thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Steffon_Baratheon",
    "pageTitle": "Steffon Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Father of Robert, Stannis, and Renly."
  },
  "cassana_baratheon": {
    "image": "./assets/portraits/generated/cassana_baratheon.webp",
    "fallback": "./assets/portraits/generated/cassana_baratheon.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Stormlands lady with chestnut hair, clear eyes, and dignified green-and-gold Estermont court dress."
  },
  "robert_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/4/43/Robert_crop.png/revision/latest/scale-to-width-down/423?cb=20210223122212",
    "fallback": "./assets/portraits/generated/robert_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Robert_Baratheon",
    "pageTitle": "Robert Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Overthrew Aerys II and sat the Iron Throne."
  },
  "stannis_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/2/2f/StannisNew.png/revision/latest/scale-to-width-down/387?cb=20210313165449",
    "fallback": "./assets/portraits/generated/stannis_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Stannis_Baratheon",
    "pageTitle": "Stannis Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Robert's brother and lawful claimant by strict succession."
  },
  "renly_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/f/ff/Profile-Renly_Baratheon.png/revision/latest/scale-to-width-down/328?cb=20171006064500",
    "fallback": "./assets/portraits/generated/renly_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Renly_Baratheon",
    "pageTitle": "Renly Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Youngest Baratheon brother and rival claimant."
  },
  "shireen_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/e/eb/Shireen_Baratheon_Season_4_profile.jpg/revision/latest/scale-to-width-down/369?cb=20210722092809",
    "fallback": "./assets/portraits/generated/shireen_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Shireen_Baratheon",
    "pageTitle": "Shireen Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Stannis's daughter."
  },
  "gendry": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/7/7b/GendryBaratheon.png/revision/latest/scale-to-width-down/373?cb=20190520221935",
    "fallback": "./assets/portraits/generated/gendry.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Gendry_Baratheon",
    "pageTitle": "Gendry Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Robert's son, acknowledged as Baratheon in the show."
  },
  "tywin_lannister": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/7/71/Tywin_Lannister_4x08.jpg/revision/latest/scale-to-width-down/348?cb=20170830015346",
    "fallback": "./assets/portraits/generated/tywin_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Tywin_Lannister",
    "pageTitle": "Tywin Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Lord of Casterly Rock and architect of Lannister power."
  },
  "joanna_lannister": {
    "image": "./assets/portraits/generated/joanna_lannister.webp",
    "fallback": "./assets/portraits/generated/joanna_lannister.svg",
    "sourceType": "generated",
    "sourceLabel": "Generated book-trait portrait",
    "sourceName": "Original generated asset",
    "sourceUrl": "",
    "pageTitle": "",
    "generatedTraits": "Golden-haired Lannister noblewoman with green eyes, elegant poise, and crimson-and-gold court dress."
  },
  "cersei_lannister": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/b/b0/CERSEIBATTLEOFKINGSLANDING.PNG/revision/latest/scale-to-width-down/338?cb=20190906021534",
    "fallback": "./assets/portraits/generated/cersei_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Cersei_Lannister",
    "pageTitle": "Cersei Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Queen to Robert, then show ruler after Tommen."
  },
  "jaime_lannister": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/5/51/JaimeLannisterSeason8.PNG/revision/latest/scale-to-width-down/317?cb=20190207112813",
    "fallback": "./assets/portraits/generated/jaime_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Jaime_Lannister",
    "pageTitle": "Jaime Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Kingslayer and secret father of Cersei's children."
  },
  "tyrion_lannister": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/9/95/HandoftheKingTyrionLannister.PNG/revision/latest/scale-to-width-down/330?cb=20190520175204",
    "fallback": "./assets/portraits/generated/tyrion_lannister.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Tyrion_Lannister",
    "pageTitle": "Tyrion Lannister",
    "generatedTraits": "golden blond hair, green eyes, aristocratic features, crimson and gold clothing; Lannister exile and political strategist."
  },
  "joffrey_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/2/25/Joffrey_Season_4_Episode_2_TLATR.jpg/revision/latest/scale-to-width-down/301?cb=20210722092942",
    "fallback": "./assets/portraits/generated/joffrey_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Joffrey_Baratheon",
    "pageTitle": "Joffrey Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Legally Robert's heir; biologically Jaime and Cersei's son."
  },
  "myrcella_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/0/02/MyrcellaS5Cropped.jpg/revision/latest/scale-to-width-down/339?cb=20160802025401",
    "fallback": "./assets/portraits/generated/myrcella_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Myrcella_Baratheon",
    "pageTitle": "Myrcella Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Princess sent to Dorne."
  },
  "tommen_baratheon": {
    "image": "https://static.wikia.nocookie.net/gameofthrones/images/7/7c/Tommen_blood_of_my_blood.jpg/revision/latest/scale-to-width-down/377?cb=20160530234845",
    "fallback": "./assets/portraits/generated/tommen_baratheon.svg",
    "sourceType": "show",
    "sourceLabel": "Show / official guide thumbnail",
    "sourceName": "Game of Thrones Wiki",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/Tommen_Baratheon",
    "pageTitle": "Tommen Baratheon",
    "generatedTraits": "black hair, strong jaw, blue eyes, broad stormland features, dark gold and black clothing; Young king after Joffrey."
  }
};
